---

# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.3
    hooks:
      - id: autopep8

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.3.0a3
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        args:
        - "--force-color"
        - "-x"
        - "106,204,701,301,305,401,303,"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
      - id: isort
        args:
          - --filter-files

  # - repo: local
  #   hooks:
  #     - id: ansible-lint
  #       name: Ansible-lint
  #       description: This hook runs ansible-lint.
  #       entry: ansible-lint --force-color -x 204,701,301,305,401,303
  #       files: ./*.yml
  #       types: [file, yaml]
  #       language: python
  #       pass_filenames: true
  #       always_run: true
